### ISSUE TITLE
PA review

### ISSUE THREAD

**Issue by NEvans85** [NEvans85/Arcane-Laboratory#32]
Deck builder is accessed through clicking on deck builder (in the nav bar) then clicking a deck (each of which is owned by the current user).

**Comment by s-pangburn** [comment]
Excellent job here, I love the attention to detail!

Maybe have the card entry change color on click to indicate it's been added successfully - I had to scroll down and check to make sure the card was added. In the interest of time, I'll close this issue, just make sure to get around to it sometime today or this weekend!
